/**
 * Smithery registry submission.
 *
 * Smithery has a hosted registry with a free tier (25k RPC calls/month).
 * Server definitions live in a `smithery.yaml` profile that is either deployed
 * with their CLI or registered through their public API.
 *
 * We support both: `submitProfile` registers the server definition, and the
 * MCP package's `deployToSmithery` handles the actual rollout.
 */

import type { RegistrySubmission, RegistryTarget } from '@agentready/shared';
import { config, errorMessage, hasApiKey, newId, registryLimiter } from '@agentready/shared';

export const SMITHERY_TARGET: RegistryTarget = {
  name: 'smithery',
  label: 'Smithery',
  url: 'https://smithery.ai',
  limits: '25,000 RPC calls / month (free tier)',
  docs: 'https://smithery.ai/docs',
  authRequired: true,
};

/** Smithery's public registry/search endpoint. */
export const SMITHERY_API = 'https://smithery.ai/api';

export interface SmitherySubmitInput {
  serverName: string;
  description: string;
  /** Streamable HTTP endpoint, once deployed. */
  serverUrl?: string;
  toolNames?: string[];
  profile?: string;
  apiKey?: string;
  /** Only validate and report. */
  dryRun?: boolean;
  fetchImpl?: typeof fetch;
  signal?: AbortSignal;
}

/** Build the `smithery.yaml` a Smithery deployment expects. */
export function buildSmitheryProfile(input: {
  serverName: string;
  description: string;
  toolNames?: string[];
  configSchema?: Record<string, unknown>;
}): string {
  const lines = [
    '# Generated by AgentReady',
    '# Deploy with: npx @smithery/cli@latest deploy',
    '',
    'startCommand:',
    '  type: stdio',
    '  configSchema:',
    `    type: object`,
    ...(input.configSchema
      ? [`    required: []`, `    properties: ${JSON.stringify(input.configSchema)}`]
      : ['    required: []', '    properties: {}']),
    '',
    '# smithery.yaml also accepts a command block when the server is not stdio.',
    '# AgentReady servers are stdio by default and are exposed over streamable-http',
    '# by Smithery automatically.',
    '',
  ];
  return lines.join('\n');
}

/** Public server URL for a Smithery-hosted server. */
export function smitheryServerUrl(profile: string, serverName: string): string {
  return `https://smithery.ai/${profile}/${serverName}`;
}

/**
 * Register a server definition with Smithery.
 *
 * Smithery's write API requires an account key; without one we return the
 * profile and the exact deploy command so the user is never blocked.
 */
export async function submitToSmithery(input: SmitherySubmitInput): Promise<RegistrySubmission> {
  const cfg = config();
  const apiKey = input.apiKey ?? cfg.smithery.apiKey;
  const profile = input.profile ?? cfg.smithery.profile;
  const serverName = input.serverName;
  const submissionId = newId('reg');
  const profileYaml = buildSmitheryProfile({
    serverName,
    description: input.description,
    ...(input.toolNames ? { toolNames: input.toolNames } : {}),
  });

  if (input.dryRun) {
    return {
      id: submissionId,
      serverName,
      name: 'smithery',
      status: 'dry-run',
      url: smitheryServerUrl(profile, serverName),
      submittedAt: new Date().toISOString(),
      logs: [
        '[dry-run] would write smithery.yaml:',
        profileYaml.split('\n').map((l) => `  ${l}`).join('\n'),
        `[dry-run] would register at ${SMITHERY_API}/v1/servers`,
      ],
    };
  }

  if (!hasApiKey(apiKey)) {
    return {
      id: submissionId,
      serverName,
      name: 'smithery',
      status: 'pending',
      url: smitheryServerUrl(profile, serverName),
      submittedAt: new Date().toISOString(),
      logs: [
        'SMITHERY_API_KEY is not set, so nothing was submitted.',
        '1. Create a key at https://smithery.ai/account/api-keys',
        '2. npx @smithery/cli@latest login',
        '3. agentready publish --target smithery',
        '',
        'Free tier: 25,000 RPC calls/month.',
      ],
      response: { profileYaml },
    };
  }

  try {
    await registryLimiter.take();
    const res = await (input.fetchImpl ?? fetch)(`${SMITHERY_API}/v1/servers`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-smithery-key': apiKey,
      },
      body: JSON.stringify({
        name: serverName,
        description: input.description,
        profile,
        ...(input.serverUrl ? { url: input.serverUrl } : {}),
        ...(input.toolNames ? { tools: input.toolNames } : {}),
      }),
      ...(input.signal ? { signal: input.signal } : {}),
    });

    const text = await res.text();
    let body: unknown = text;
    try {
      body = text ? JSON.parse(text) : undefined;
    } catch {
      /* keep raw text */
    }

    if (res.ok || res.status === 202) {
      return {
        id: submissionId,
        serverName,
        name: 'smithery',
        status: 'submitted',
        url: smitheryServerUrl(profile, serverName),
        submittedAt: new Date().toISOString(),
        response: body,
        logs: [
          `Registered ${serverName} on Smithery (HTTP ${res.status}).`,
          'Roll it out with: npx @smithery/cli@latest deploy ' + serverName,
        ],
      };
    }

    return {
      id: submissionId,
      serverName,
      name: 'smithery',
      status: 'error',
      error: `Smithery returned HTTP ${res.status}: ${text.slice(0, 300)}`,
      submittedAt: new Date().toISOString(),
      response: body,
      logs: ['Confirm the API key is valid at https://smithery.ai/account/api-keys'],
    };
  } catch (err) {
    return {
      id: submissionId,
      serverName,
      name: 'smithery',
      status: 'error',
      error: errorMessage(err),
      submittedAt: new Date().toISOString(),
      logs: ['Could not reach the Smithery API.'],
    };
  }
}

/** Search Smithery for existing servers. */
export async function searchSmithery(
  query: string,
  opts: { limit?: number; fetchImpl?: typeof fetch; signal?: AbortSignal } = {},
): Promise<Array<Record<string, unknown>>> {
  try {
    await registryLimiter.take();
    const res = await (opts.fetchImpl ?? fetch)(
      `${SMITHERY_API}/v1/servers?search=${encodeURIComponent(query)}&pageSize=${opts.limit ?? 20}`,
      { headers: { accept: 'application/json' }, ...(opts.signal ? { signal: opts.signal } : {}) },
    );
    if (!res.ok) return [];
    const body = (await res.json()) as { servers?: Array<Record<string, unknown>> };
    return body.servers ?? [];
  } catch {
    return [];
  }
}

/** Read a server's page and confirm it is deployed. */
export async function fetchSmitheryStatus(
  profile: string,
  serverName: string,
  opts: { fetchImpl?: typeof fetch; signal?: AbortSignal } = {},
): Promise<{ deployed: boolean; detail: string }> {
  try {
    await registryLimiter.take();
    const res = await (opts.fetchImpl ?? fetch)(`${SMITHERY_API}/v1/servers/${profile}/${serverName}`, {
      headers: { accept: 'application/json' },
      ...(opts.signal ? { signal: opts.signal } : {}),
    });
    if (res.status === 404) return { deployed: false, detail: 'not found on Smithery' };
    if (!res.ok) return { deployed: false, detail: `HTTP ${res.status}` };
    const body = (await res.json()) as Record<string, unknown>;
    return {
      deployed: true,
      detail: String(body['status'] ?? body['deploymentStatus'] ?? 'listed'),
    };
  } catch (err) {
    return { deployed: false, detail: errorMessage(err) };
  }
}